{
 "title": "windows server sql servers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gp",
    "label": "group",
    "query": {}
   },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Uptime" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "itServiceFilter": "$gp",
     "item": { "filter": "/ICMP.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "1h",
     "slaProperty": { "name": "Status", "property": "status" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Cpu Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of cores" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Used memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Queue Length",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU queue length" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used Swap Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Used swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Privileged Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU privileged time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu User Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU user time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interface Bits Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Interface .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Bits received/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Swap Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total swap space" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Queue Length(percentile 2days - 95%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "$$hashKey": "object:211",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         95
        ],
        "name": "percentile",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "percent",
          "options": [
           25,
           50,
           75,
           90,
           95,
           99,
           99.9
          ],
          "type": "float"
         }
        ]
       },
       "params": [
        "2d",
        95
       ],
       "text": "percentile(2d, 95)"
      }
     ],
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU queue length" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interface Bits Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Interface .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Bits sent/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Average Read Queue Length",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Average disk read queue length/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Average Write Queue Length",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Average disk write queue length/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Used Space",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Space utilization/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Total Space",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Total space/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "SQL Server Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "SQL Server Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "SQL MSSQLSERVER Server Services"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "SQL Instance MSSQLSERVER Server: Service State"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Latch Wait Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": {
      "filter": "SQL MSSQLSERVER Users And Locks"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "SQL Instance MSSQLSERVER: Total Latch Wait Time (ms)"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Databases Status",
   "type": "stat",
   "description": "0 = Online\n1 = Restoring\n2 = Recovering: SQL Server 2008 through SQL Server 2017\n3 = Recovery pending : SQL Server 2008 through SQL Server 2017\n4 = Suspect \n5 = Emergency: SQL Server 2008 through SQL Server 2017\n6 = Offline: SQL Server 2008 through SQL Server 2017\n7 = Copying : Azure SQL Database Active Geo-Replication \n10 = Offline Secondary : Azure SQL Database Active Geo-Replication\n21 = Mirrored, Secondary Synchronized\n23 = Mirrored, Principal, Synchronized\n25 = Mirrored, Secondary, Not Synchronized\n26 = Mirrored, Principal, Not Synchronized\n31 = Always On, Synchronized\n35 = Always On, Not Synchronized\n40 = Log Shipping, Standby / Read-Only\n41 = Log Shipping, Restoring\n42 = Log Shipping, Recovering",
   "gridPos": { "h": 21, "w": 16, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Database .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .* Database .*: Status/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Processes Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Users And Locks/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .*: Processes Blocked/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Memory Manager/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .*: Total Server Memory \\(KB\\)/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Longest Transaction Running Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Users And Locks/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .*: Longest Transaction RunningTime/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Maximum Workspace Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Memory Manager/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .*: Maximum Workspace Memory \\(KB\\)/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Database Pages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Memory Usage/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .*: Database Pages/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Cache Pages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "SQL MSSQLSERVER Plan Cache" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "SQL Instance MSSQLSERVER: Cache Pages"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Page Life Expectancy(PLE)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": {
      "filter": "/SQL .* Buffer Manager And Memory/"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .*: Page Life Expectancy/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active Cursors Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "SQL MSSQLSERVER Workload" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "SQL Instance MSSQLSERVER: Active Cursors _Total"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Buffer Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": {
      "filter": "/SQL .* Buffer Manager And Memory/"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .*: Buffer cache hit ratio %/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Users And Locks/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .*: User Connections/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Log Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Database .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .* Database .*: Percent Log Used/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Full Backup Status",
   "type": "stat",
   "description": "\t0 ⇒ Backup status unavailable\n1 ⇒ Backup is not older then 25 hours\n2 ⇒ Backup is older then 25 hours\n3 ⇒ Backup is older then 26 hours\n4 ⇒ Backup is older then 27 hours\n6 ⇒ Backup is not older then 7 days and 4 hours\n7 ⇒ Backup is older then 7 days and 4 hours\n8 ⇒ Backup is older then 7 days and 6 hours\n9 ⇒ Backup is older then 7 days and 8 hours\n11 ⇒ Backup is not older then 25 hours\n12 ⇒ Backup is older then 25 hours\n13 ⇒ Backup is older then 26 hours\n14 ⇒ Backup is older then 27 hours\n16 ⇒ Backup is not older then 30 minutes\n17 ⇒ Backup is older then 30 minutes\n18 ⇒ Backup is older then 60 minutes\n19 ⇒ Backup is older then 90 minutes",
   "gridPos": { "h": 23, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL MSSQLSERVER Database .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .* Database .*: Full Backup Status/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Diff Backup Status",
   "type": "stat",
   "description": "\t0 ⇒ Backup status unavailable\n1 ⇒ Backup is not older then 25 hours\n2 ⇒ Backup is older then 25 hours\n3 ⇒ Backup is older then 26 hours\n4 ⇒ Backup is older then 27 hours\n6 ⇒ Backup is not older then 7 days and 4 hours\n7 ⇒ Backup is older then 7 days and 4 hours\n8 ⇒ Backup is older then 7 days and 6 hours\n9 ⇒ Backup is older then 7 days and 8 hours\n11 ⇒ Backup is not older then 25 hours\n12 ⇒ Backup is older then 25 hours\n13 ⇒ Backup is older then 26 hours\n14 ⇒ Backup is older then 27 hours\n16 ⇒ Backup is not older then 30 minutes\n17 ⇒ Backup is older then 30 minutes\n18 ⇒ Backup is older then 60 minutes\n19 ⇒ Backup is older then 90 minutes",
   "gridPos": { "h": 23, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL MSSQLSERVER Database .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .* Database .*: Diff Backup Status/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Log Backup Status",
   "type": "stat",
   "description": "\t0 ⇒ Backup status unavailable\n1 ⇒ Backup is not older then 25 hours\n2 ⇒ Backup is older then 25 hours\n3 ⇒ Backup is older then 26 hours\n4 ⇒ Backup is older then 27 hours\n6 ⇒ Backup is not older then 7 days and 4 hours\n7 ⇒ Backup is older then 7 days and 4 hours\n8 ⇒ Backup is older then 7 days and 6 hours\n9 ⇒ Backup is older then 7 days and 8 hours\n11 ⇒ Backup is not older then 25 hours\n12 ⇒ Backup is older then 25 hours\n13 ⇒ Backup is older then 26 hours\n14 ⇒ Backup is older then 27 hours\n16 ⇒ Backup is not older then 30 minutes\n17 ⇒ Backup is older then 30 minutes\n18 ⇒ Backup is older then 60 minutes\n19 ⇒ Backup is older then 90 minutes",
   "gridPos": { "h": 23, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL MSSQLSERVER Database .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .* Database .*: Log Backup Status/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU queue length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU queue length" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Detail Metrics",
   "type": "timeseries",
   "description": "user time - privileged time - DPC time - interrupt time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/CPU (user.*|interrupt.*|privileged .*|DPC.*)/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Used memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Cache bytes" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory page faults per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memory page faults per second" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Pool Non-Paged",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memory pool non-paged" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Average Disk Read Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.* Average disk read queue length/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Average disk write queue length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Average disk write queue length/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Disk read rate/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 133 },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Disk write rate/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Read Request Avg Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.* Disk read request avg waiting time/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Write Request Avg Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.* Disk write request avg waiting time/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Interfaces Bits Received",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 154 },
   "targets": [
    {
     "application": { "filter": "/Interface.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Bits received/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfaces Bits Sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 154 },
   "targets": [
    {
     "application": { "filter": "/Interface.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Bits sent/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfaces Inbound Packets With Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "application": { "filter": "/Interface.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Inbound packets with errors/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfaces Inbound Packets Discarded",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 164 },
   "targets": [
    {
     "application": { "filter": "/Interface.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Inbound packets discarded/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfaces Outbound Packets With Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 174 },
   "targets": [
    {
     "application": { "filter": "/Interface.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Outbound packets with errors/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfaces Outbound Packets Discarded",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 174 },
   "targets": [
    {
     "application": { "filter": "/Interface.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Outbound packets discarded/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "SQL Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "Databases Data File Size",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL MSSQLSERVER Database .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .* Database .* Data File\\(s\\) Size \\(KB\\)/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Databases Log File Size",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/SQL .* Database .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .* Database .*: Log File\\(s\\) Used Size \\(KB\\)/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Queries and Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "SQL MSSQLSERVER Workload" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Pages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": {
      "filter": "SQL MSSQLSERVER Buffer Manager And Memory"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "SQL MSSQLSERVER Workload" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance .* Errors/sec .*/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Databases Active Transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "/SQL MSSQLSERVER Database .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SQL Instance MSSQLSERVER Database .*: Active Transactions/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "SQL MSSQLSERVER Statistics" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Users and Blocked Processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": {
      "filter": "SQL MSSQLSERVER Users And Locks"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": {
      "filter": "SQL MSSQLSERVER Server Services"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Manager",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "SQL MSSQLSERVER Memory Manager" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Data Access",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "SQL MSSQLSERVER Data Access" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "SQL MSSQLSERVER Plan Cache" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lock and Latch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": {
      "filter": "SQL MSSQLSERVER Users And Locks"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lock and Latch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": {
      "filter": "SQL MSSQLSERVER Users And Locks"
     },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}