{
 "title": "Top 10's",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hosts.name AS \"hostname\",\n  avg(value) AS \"utilization\"\nFROM items \nJOIN hosts ON (hosts.hostid = items.hostid)\nJOIN history ON (items.itemid = history.itemid)\nWHERE\n  clock > UNIX_TIMESTAMP() - 300 \nAND\n  items.name=\"Memory utilization\"\nGROUP BY items.itemid\nORDER BY utilization desc\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hosts.name AS \"hostname\",\n  avg(value) AS \"utilization\"\nFROM items \nJOIN hosts ON (hosts.hostid = items.hostid)\nJOIN history ON (items.itemid = history.itemid)\nWHERE\n  clock > UNIX_TIMESTAMP() - 300 \nAND\n  items.name=\"CPU utilization\"\nGROUP BY items.itemid\nORDER BY utilization desc\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Disk Space ( C - / )",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hosts.name AS \"hostname\",\n  items.name,\n  avg(value) AS \"utilization\"\nFROM items \nJOIN hosts ON (hosts.hostid = items.hostid)\nJOIN history ON (items.itemid = history.itemid)\nWHERE\n  clock > UNIX_TIMESTAMP() - 300 \nAND\n  items.name = \"C:: Space utilization\"\nOR \n  items.name = \"/: Space utilization\"\nGROUP BY items.itemid\nORDER BY utilization desc\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hosts.name AS \"hostname\",\n  items.name,\n  avg(value) AS \"utilization\"\nFROM items \nJOIN hosts ON (hosts.hostid = items.hostid)\nJOIN history ON (items.itemid = history.itemid)\nWHERE\n  clock > UNIX_TIMESTAMP() - 300 \nAND\n  items.name = \"C:: Space utilization\"\nOR \n  items.name = \"D:: Space utilization\"\nOR \n  items.name = \"E:: Space utilization\"\nOR \n  items.name = \"F:: Space utilization\"\nOR \n  items.name = \"H:: Space utilization\"\nOR \n  items.name = \"G:: Space utilization\"\nOR \n  items.name = \"I:: Space utilization\"\nOR \n  items.name = \"/: Space utilization\"\nGROUP BY items.itemid\nORDER BY utilization desc\nLIMIT 10;"
    }
   ]
  }
 ]
}