{
 "title": "zabbix servers - linux",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "gp",
    "label": "group",
    "query": {}
   },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Zabbix Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zabbix Agent Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Zabbix agent .*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Configuration Cache Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*: Configuration cache, % used/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "History Index Cache Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*: History index cache, % used/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VMware Cache Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*: VMware cache, % used/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number Of Processed * Values per Second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*: Number of processed .* values per second/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "* Cache Used",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*cache, % used/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number Of Processed * Values per Second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*: Value cache .*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Utilizations Of All",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*: Utilization .*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "System uptime" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 53 },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "itServiceFilter": "$gp",
     "item": { "filter": "/ICMP.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "1h",
     "slaProperty": { "name": "Status", "property": "status" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Cpu Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of CPUs" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interface Bits Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Interface .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Bits sent/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Privileged Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu System Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU system time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu User Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU user time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Swap Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total swap space" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interface Bits Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Interface .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Bits received/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Load Average",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Load average.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfaces Operational Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "/Interface .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Interface .*: Operational status/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Load Average Percentile(2days, 95)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "$$hashKey": "object:986",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         95
        ],
        "name": "percentile",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "percent",
          "options": [
           25,
           50,
           75,
           90,
           95,
           99,
           99.9
          ],
          "type": "float"
         }
        ]
       },
       "params": [
        "2d",
        95
       ],
       "text": "percentile(2d, 95)"
      }
     ],
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Load average.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Total Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Total space/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Used Space",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Space utilization/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Inodes ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Free inodes in %/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "CPU utilization" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "CPU Load Average",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Load average .*/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Detail Metrics",
     "type": "timeseries",
     "description": "user time - privileged time - DPC time - interrupt time",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Detail Metrics",
     "type": "timeseries",
     "description": "user time - privileged time - DPC time - interrupt time",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/(Context switches per second|Interrupts per second)/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "Memory utilization" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Free Swap Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "Total swap space" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "Free swap space" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interfaces Bits Received",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Bits received/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Bits Sent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Bits sent/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Inbound Packets With Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/.*Inbound packets with errors/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Inbound Packets Discarded",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Inbound packets discarded/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Outbound Packets With Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/.*Outbound packets with errors/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Outbound Packets Discarded",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Outbound packets discarded/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}