{
 "title": "windows server IIS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gp",
    "label": "group",
    "query": {}
   },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "IIS Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "IIS: Uptime" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "IIS AppPools State",
     "type": "stat",
     "description": "\t1 ⇒ Uninitialized\n2 ⇒ Initialized\n3 ⇒ Running\n4 ⇒ Disabling\n5 ⇒ Disabled\n6 ⇒ Shutdown Pending\n7 ⇒ Delete Pending",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/IIS: AppPool .* state/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Service W3SVC State",
     "type": "stat",
     "description": "Provides Web connectivity and administration through IIS Manager",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "IIS: World Wide Web Publishing Service (W3SVC) state"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "IIS: Current connections" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Service WAS State",
     "type": "stat",
     "description": "Provides process activation, resource and health management services for message-activated applications.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "IIS: Windows Process Activation Service (WAS) state"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Connection Attempts Per Second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "IIS: Connection attempts per second"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "IIS Port Ping(default 80)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "IIS: {$IIS.PORT} port ping" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Total Bytes Per Second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "IIS: Bytes Total per second" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "AppPools Queue Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/IIS: AppPool .* queue size/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Total Requests Per Second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "IIS: Method Total requests per second"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "File Cache Misses",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "IIS: File cache misses" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Locked Errors Per Second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "IIS: Locked errors per second" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Files Cache Hits",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "IIS: Files cache hits percentage"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "URIs Cache Hits ",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "IIS: URIs cache hits percentage"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "AppPools Recycles",
     "type": "stat",
     "description": "Recycling means that the worker process that handles requests for that application pool is terminated",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/IIS: AppPool .* recycles/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Not Found Errors Per Second",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "IIS: Not Found errors per second"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Uptime" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 2 },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "itServiceFilter": "$gp",
     "item": { "filter": "/ICMP.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "1h",
     "slaProperty": { "name": "Status", "property": "status" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Cpu Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of cores" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Used memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Queue Length",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU queue length" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used Swap Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Used swap space in %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Privileged Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU privileged time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu User Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU user time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interface Bits Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Interface .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Bits received/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Swap Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total swap space" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cpu Queue Length(percentile 2days - 95%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "$$hashKey": "object:211",
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         95
        ],
        "name": "percentile",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "percent",
          "options": [
           25,
           50,
           75,
           90,
           95,
           99,
           99.9
          ],
          "type": "float"
         }
        ]
       },
       "params": [
        "2d",
        95
       ],
       "text": "percentile(2d, 95)"
      }
     ],
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU queue length" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interface Bits Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Interface .*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Bits sent/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Average Read Queue Length",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Average disk read queue length/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Average Write Queue Length",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Disk.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Average disk write queue length/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Used Space",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Space utilization/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disks Total Space",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem.*/" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Total space/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU queue length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU queue length" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Detail Metrics",
   "type": "timeseries",
   "description": "user time - privileged time - DPC time - interrupt time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$gp" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/CPU (user.*|interrupt.*|privileged .*|DPC.*)/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "Total memory" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "Used memory" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Cache Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "Cache bytes" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Memory page faults per second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "Memory page faults per second" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Memory Pool Non-Paged",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "Memory pool non-paged" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Disk Read Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "application": { "filter": "/Disk.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/.* Average disk read queue length/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Average disk write queue length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "application": { "filter": "/Disk.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/.*Average disk write queue length/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Disk Read Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "application": { "filter": "/Disk.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Disk read rate/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Disk Write Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "application": { "filter": "/Disk.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.* Disk write rate/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Disks Read Request Avg Waiting Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "application": { "filter": "/Disk.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/.* Disk read request avg waiting time/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Disk Write Request Avg Waiting Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "application": { "filter": "/Disk.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/.* Disk write request avg waiting time/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interfaces Bits Received",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Bits received/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Bits Sent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Bits sent/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Inbound Packets With Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/.*Inbound packets with errors/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Inbound Packets Discarded",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Inbound packets discarded/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Outbound Packets With Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/.*Outbound packets with errors/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interfaces Outbound Packets Discarded",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "application": { "filter": "/Interface.*/" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*Outbound packets discarded/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "IIS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received/Sent per second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": { "filter": "/IIS: Bytes.*/" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Anonymous/NonAnonymous Users Per Second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/IIS: (Anonymous|NonAnonymous) users per second/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Methods Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "IIS" },
       "group": { "filter": "$gp" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/IIS: Method .* requests per second/"
       },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}